
spring.datasource.url=jdbc:postgresql://localhost:5432/HoopdojoTEST1
spring.datasource.username=postgres
spring.datasource.password=Use_your_own_password_sillygoose

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update